script sidu-control moved to sidu-base

diff --git a/bin/pywwetha-control b/bin/pywwetha-control
--- a/bin/pywwetha-control
+++ b/bin/pywwetha-control
@@ -1,3 +1,7 @@
-#! /bin/sh
-
-sudo sidu-control systemctl pywwetha $1
+#! /bin/bash
+if [ ! -x /usr/bin/sidu-control ] ; then
+	echo "cannot execute pywwetha-control: sidu-control (from sidu-base) is not installed"
+	exit 1
+else
+	sidu-control systemctl pywwetha $1
+fi
